---

- name: copy DB init
  copy:
    src: "{{ role_path }}/files/initdb.sql"
    dest: /root/initdb.sql

- name: mariadb container
  docker_container:
    name: some-mariadb
    image: library/mariadb
    state: started
    volumes:
      - /root/initdb.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/lib/mysql
    env:
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    restart_policy: unless-stopped
    
- name: guacd container
  docker_container:
    name: some-guacd
    image: guacamole/guacd
    state: started
    restart_policy: unless-stopped

- name: guacamole container
  docker_container:
    name: guacamole
    image: guacamole/guacamole
    state: started
    ports: 8080:8080
    links:
      - some-guacd:guacd
      - some-mariadb:mysql
    env:
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    restart_policy: unless-stopped